### ISSUE TITLE
Host and Port information are missing

### ISSUE THREAD

**Issue by vfrride** [Kloadut/dokku-pg-plugin#76]
For some reason dokku seems to have forgotten my Host and Port information.

When I execute

```
dokku postgresql:info
```

I get:

```

docker: "inspect" requires a minimum of 1 argument.
See 'docker inspect --help'.

Usage: docker inspect [OPTIONS] CONTAINER|IMAGE [CONTAINER|IMAGE...]

Return low-level information on a container or image
json: cannot unmarshal array into Go value of type struct { NetworkSettings struct { Ports nat.PortMap } }

       Host:
       Port:
       User: 'root'
       Password: '<redacted>'
       Database: 'db'

       Url: 'postgres://root:<redacted>@:/db'
```

When I try to start up my rails app I get:

```
URI::InvalidURIError: the scheme postgres does not accept registry part: root:<redacted>@<redacted>:32769: (or bad hostname?)
```

This all worked yesterday, and I can connect to the database using the credentials above, but when I tried to update my dokku version this started happening.

Dokku v0.3.18-80-gc0f8764
dokku-pg-plugin 35edfebd9bc4eafcdf9f3ecfc32cef3404853b9b

Any help would be greatly appreciated!
